version: '3'
services:
  ach:
    image: moov/ach:v1.0.2
    ports:
      - "8080:8080"
  accounts:
    image: moov/accounts:v0.4.0-dev
    ports:
      - "8085:8085"
    environment:
      DEFAULT_ROUTING_NUMBER: '121042882'
  fed:
    image: moov/fed:v0.2.0
    ports:
      - "8086:8086"
    environment:
      FEDACH_DATA_PATH: './data/fed/FedACHdir.txt'
      FEDWIRE_DATA_PATH: './data/fed/fpddir.txt'
  ofac:
    image: moov/ofac:v0.9.0
    ports:
      - "8084:8084"
  auth:
    image: moov/auth:v0.7.0
    ports:
      - "8081:8081"
  paygate:
    image: moov/paygate:latest
    ports:
      - "8082:8082"
      - "9092:9092"
    command: ["-http.addr", ":8082"]
    environment:
      ACCOUNTS_ENDPOINT: 'http://accounts:8085'
      ACH_ENDPOINT: 'http://ach:8080'
      FED_ENDPOINT: 'http://fed:8086'
      OFAC_ENDPOINT: 'http://ofac:8084'
    depends_on:
      - ach
      - accounts
      - fed
      - ofac
      - auth
